print(3 + 4)
print(3 - 4) 
print(3 * 4)
print(3 / 2)
print(3 % 4)
print(3 ** 4)
print(3 // 4)
print("Carolina")
print("Colombo Cuellar")
print("España")
print("I am enjoying 30 days of python")
print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4 - 4j))
print(type("Carolina" "Colombo Cuellar" "España"))
print(type("Carolina"))
print(type("Colombo Cuellar"))
print(type("España"))
print(28)
print(5.4)
print(5 + l)
print(i love pizza)
print(True)#Is the light on? If it is on, then the value is True
print(False)#Is the light on? If it is off, then the value is False
print[0,1,2]
